const jobSearchCst = {
    JOB_ADD : "JOB_ADD",
    JOB_UPDATE : "JOB_UPDATE",
    JOB_UPDATE_DONE : "JOB_UPDATE_DONE",
    JOB_UPDATE_CANCEL : "JOB_UPDATE_CANCEL",
    JOB_DISPLAY_LIST : "JOB_DISPLAY_LIST",
    JOB_DISPLAY_ONE : "JOB_DISPLAY_ONE",
    JOB_DISPLAY_ONE_CLOSE : "JOB_DISPLAY_ONE_CLOSE",
    
    JOB_SET_PENDING : "JOB_SET_PENDING",
    JOB_SET_MISSED : "JOB_SET_MISSED",
    JOB_SET_SORT_COMPANY_BY_NAME : "JOB_SET_SORT_COMPANY_BY_NAME",
    JOB_SET_RECENT_FIRST : "JOB_SET_RECENT_FIRST"
}

export default jobSearchCst