export const AUTH_USER = 'auth_user';
export const AUTH_ERROR = 'auth_error';

export const SERVER_CST = {
    JOB_DISPLAY_PENDING: "JOB_DISPLAY_PENDING",
    JOB_DISPLAY_MISSED: "JOB_DISPLAY_MISSED",

    COMPANY_TYPE_HIRING: "DIRECT_HIRING",
    COMPANY_TYPE_JOBS_LISTER: "JOBS_LISTER",
    COMPANY_TYPE_JOBS_NO_IDEA: "NO_IDEA"
};
