module.exports = {
    JOB_STATUS_PENDING: "JOB_STATUS_PENDING",
    JOB_STATUS_MISSED: "JOB_STATUS_MISSED",

    COMPANY_TYPE_HIRING: "DIRECT_HIRING",
    COMPANY_TYPE_JOBS_LISTER: "JOBS_LISTER",
    COMPANY_TYPE_JOBS_NO_IDEA: "NO_IDEA"
};